<?xml version="1.0"?>
<robot name="parobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_separation" value="0.40"/>
  <xacro:property name="base_radius" value="0.20"/>

  <!-- BASE LINK -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="${base_radius}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.3 0.3 0.3 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <!-- âœ… all inertia terms must be present -->
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0"/>
    </inertial>
  </link>

  <!-- LEFT WHEEL -->
  <link name="left_wheel_link">
    <visual>
      <geometry>
        <cylinder length="0.04" radius="${wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.04" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="left_wheel_link"/>
    <!-- x forward, y left, z up; wheel_separation/2 is fine once xacro runs -->
    <origin xyz="0.0 ${wheel_separation/2.0} ${wheel_radius}" rpy="${pi/2} 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- RIGHT WHEEL -->
  <link name="right_wheel_link">
    <visual>
      <geometry>
        <cylinder length="0.04" radius="${wheel_radius}"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.04" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="right_wheel_link"/>
    <origin xyz="0.0 -${wheel_separation/2.0} ${wheel_radius}" rpy="${pi/2} 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- CAMERA -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
  </link>

  <joint name="base_to_camera" type="fixed">
    <parent link="base_link"/>
    <child  link="camera_link"/>
    <origin xyz="0.0 0.0 0.8" rpy="0 0 0"/>
  </joint>

  <!-- LIDAR -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="0.03"/>
      </geometry>
      <material name="green">
        <color rgba="0.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.0005" ixy="0.0" ixz="0.0"
               iyy="0.0005" iyz="0.0"
               izz="0.0005"/>
    </inertial>
  </link>

  <joint name="base_to_lidar" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="0.2 0.0 0.6" rpy="0 0 0"/>
  </joint>

</robot>
